services:
  db:
    image: postgres:16.13
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: notifications
      POSTGRES_PASSWORD: notifications
    ports:
      - "5434:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U notifications -d notifications" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: notifications
      DB_USER: notifications
      DB_PASSWORD: notifications
      API_KEY: api-key-notifications
    ports:
      - "8080:8080"

volumes:
  notification-db-data:
